"""
Daily report generator — summarize job hunting progress as Markdown.

Outputs:
  - New jobs discovered today
  - High-match jobs (score >= threshold)
  - Application status changes
  - Recommended actions
"""

from __future__ import annotations

import logging
from datetime import datetime

from jobpilot import config
from jobpilot.db import JobPilotDB
from jobpilot.tracker import get_pipeline_summary

logger = logging.getLogger(__name__)


def generate_daily_report(db: JobPilotDB, profile_id: int = 1) -> str:
    """Generate a Markdown daily report.

    Args:
        db: Database instance
        profile_id: Profile to use for score lookup

    Returns:
        Markdown string
    """
    today = datetime.now().strftime("%Y-%m-%d")
    stats = db.get_stats()
    pipeline = get_pipeline_summary(db)

    sections: list[str] = []

    # Header
    sections.append(f"# JobPilot 日报 — {today}\n")

    # Overview
    sections.append("## 概览\n")
    sections.append(f"| 指标 | 数量 |")
    sections.append(f"|------|------|")
    sections.append(f"| 岗位总数 | {stats['jobs_total']} |")
    sections.append(f"| 已评分 | {stats['jobs_scored']} |")
    sections.append(f"| 平均匹配分 | {stats['avg_score']} |")
    sections.append(f"| 投递记录 | {stats['applications']} |")
    sections.append("")

    # Pipeline
    sections.append("## 投递管道\n")
    sections.append("```")
    status_labels = {
        "new": "新发现",
        "scored": "已评分",
        "tailored": "已定制简历",
        "applied": "已投递",
        "replied": "有回复",
        "interview": "面试中",
        "offer": "Offer",
        "rejected": "已拒绝",
    }
    for status, label in status_labels.items():
        count = pipeline.get(status, 0)
        bar = "█" * count
        sections.append(f"  {label:8s} | {bar} {count}")
    sections.append("```\n")

    # Top matches
    top_scores = db.list_scores_with_jobs(
        profile_id=profile_id,
        min_score=config.MIN_RECOMMEND_SCORE,
        limit=10,
    )
    if top_scores:
        sections.append("## 推荐投递（匹配度 >= {:.0f}）\n".format(config.MIN_RECOMMEND_SCORE))
        sections.append("| 评分 | 职位 | 公司 | 城市 | 薪资 |")
        sections.append("|------|------|------|------|------|")
        for score, job in top_scores:
            salary = f"{job.salary_min // 1000}-{job.salary_max // 1000}K" if job.salary_max else "面议"
            sections.append(
                f"| {score.overall_score:.1f} | {job.title} | {job.company} | {job.city} | {salary} |"
            )
        sections.append("")

    # Recent applications
    recent_apps = db.list_applications()[:10]
    if recent_apps:
        sections.append("## 最近投递\n")
        sections.append("| 岗位ID | 状态 | 更新时间 |")
        sections.append("|--------|------|----------|")
        for app in recent_apps:
            job = db.get_job(app.job_id)
            title = job.title if job else app.job_id
            sections.append(
                f"| {title} | {status_labels.get(app.status, app.status)} | {app.updated_at} |"
            )
        sections.append("")

    # New unscored jobs
    new_jobs = db.list_jobs(status="new", limit=20)
    if new_jobs:
        sections.append(f"## 待评分岗位（{len(new_jobs)} 个）\n")
        for job in new_jobs[:10]:
            salary = f"{job.salary_min // 1000}-{job.salary_max // 1000}K" if job.salary_max else "面议"
            sections.append(f"- **{job.title}** @ {job.company} ({job.city}, {salary})")
        if len(new_jobs) > 10:
            sections.append(f"- ... 还有 {len(new_jobs) - 10} 个")
        sections.append("")

    # Footer
    sections.append("---")
    sections.append(f"*Generated by JobPilot v0.1.0 at {datetime.now().strftime('%H:%M:%S')}*")

    return "\n".join(sections)


def save_report(db: JobPilotDB, output_path: str | None = None) -> str:
    """Generate and save daily report.

    Args:
        db: Database instance
        output_path: Where to save. Default: data/report_YYYY-MM-DD.md

    Returns:
        Path to the saved report
    """
    report = generate_daily_report(db)
    if not output_path:
        today = datetime.now().strftime("%Y-%m-%d")
        output_path = str(config.DATA_DIR / f"report_{today}.md")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)

    logger.info("Report saved to %s", output_path)
    return output_path
